### ISSUE TITLE
Arduino: 1.8.19 (Windows 10), Board: "Generic ESP8266 Module, 80 MHz, Flash, Disabled (new aborts on oom), Disabled, All SSL ciphers (most compatible), 32KB cache + 32KB IRAM (balanced), Use pgm_read macros for IRAM/PROGMEM, dtr (aka nodemcu), 26 MHz, 40MHz, DOUT (compatible), 1MB (FS:64KB OTA:~470KB), 2, nonos-sdk 2.2.1+100 (190703), v2 Lower Memory, Disabled, None, Only Sketch, 115200"  sketch_dec03a:4:10: fatal error: credentials.h: No such file or directory      4 | #include "credentials.h"        |          ^~~~~~~~~~~~~~~  compilation terminated.  exit status 1  credentials.h: No such file or directory    This report would have more information with "Show verbose output during compilation" option enabled in File -> Preferences.

### ISSUE THREAD

**Issue by ajith483** [mixlaab/atom-sensorsData-ESP8266#1]

**Comment by ajith483** [comment]
Arduino: 1.8.19 (Windows 10), Board: "Generic ESP8266 Module, 80 MHz, Flash, Disabled (new aborts on oom), Disabled, All SSL ciphers (most compatible), 32KB cache + 32KB IRAM (balanced), Use pgm_read macros for IRAM/PROGMEM, dtr (aka nodemcu), 26 MHz, 40MHz, DOUT (compatible), 1MB (FS:64KB OTA:~470KB), 2, nonos-sdk 2.2.1+100 (190703), v2 Lower Memory, Disabled, None, Only Sketch, 115200"

default_encoding:       cp1252
Assume aggressive 'core.a' caching enabled.

*** Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.1.2/tools/mkbuildoptglobals.py", line 824, in <module>
    rc = main()
  File "C:\Users\Admin\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.1.2/tools/mkbuildoptglobals.py", line 728, in main
    os.makedirs(build_path_core)
  File "D:\obj\Windows-Release\37win32_Release\msi_python\zip_win32\os.py", line 221, in makedirs
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\Admin\\AppData\\Local\\Temp\\arduino_build_983511\\core'

exit status 1
Error compiling for board Generic ESP8266 Module.
sketch_dec05a:1:9: error: #include expects "FILENAME" or <FILENAME>
    1 | #include&lt;Wire.h&gt;
      |         ^
sketch_dec05a:2:10: error: #include expects "FILENAME" or <FILENAME>
    2 | #include &lt;ESP8266WiFi.h&gt;
      |          ^
sketch_dec05a:3:10: error: #include expects "FILENAME" or <FILENAME>
    3 | #include &lt;WiFiUdp.h&gt;
      |          ^
exit status 1
#include expects "FILENAME" or <FILENAME>


This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.
